dist: trusty
sudo: required
before_install:
language: python
python:
- '3.6'
script:
- echo
deploy:
  provider: pypi
  user: mikkokotila
  password:
    secure: IGRi07+tYfnKQm1iL7LKgbk8pvtg7TA5OIqGpMPTW2uJ8AslrGP5Qztcr0rUpd0+0PdEFVRdnxHJIBm5rkjC0eeusTsfndayFjFkIiHyjjBf9o9qP/CdXA22rxoshxLR9EkUwhOLhtHincQWOy4JCIxVeMjuCyjh/uQxnhqwR6brb5SZfOeZFSZD5zJ420LVgAys+wws8iYSddGC9RTjrOo9KgO4jIfFn5lbnjODqnDbWIrRC/V6iN376WuDNhV8vN4ZZnP5KBOrU3phGLKqTvZLRNWJqMvYWBJwxUX0+v65yrxMMxFLr3bRy3oP1AwZQwefhqNvgWPwObJ5riHyrjnhyaJ5TUzaKr9f8rgw5Oa7MYcUQEL+KZVz/lxxLhdCvG4/HJHUnS46/tx9B/GjW2eUyJ3BhOLP7hAvBfe87S97aDU7AQKrdxGv6nImQwe3mJSH93EYuxlXnDvzbNihibyfSbLaM1dr5RBRCbbUEaRq+xN9LrXTu3tS5OrAuccBa+jbkqRRCA2SjsjcBwtetlfibE72JES0UQcao7KDh7N9Ze5DR1HW9LklRnbK2qlYD63RrdmCOIqFFdJW9k9KmhEOtUbrNOCE+CBJQZdlN6jGkqpwZn241uQHsXKUO3ZmkA3x+E3Nl4g1i6zcEE43rfJh/4KYfQIGR5R4IWKfheM=
  on:
    branch: production
